[2023-04-30 09:51:52,255] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: multi_attack_dag.attack_CarliniL2Method manual__2023-04-30T09:46:13.115621+00:00 [queued]>
[2023-04-30 09:51:52,287] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: multi_attack_dag.attack_CarliniL2Method manual__2023-04-30T09:46:13.115621+00:00 [queued]>
[2023-04-30 09:51:52,292] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-04-30 09:51:52,293] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2023-04-30 09:51:52,294] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-04-30 09:51:52,330] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): attack_CarliniL2Method> on 2023-04-30 09:46:13.115621+00:00
[2023-04-30 09:51:52,355] {standard_task_runner.py:52} INFO - Started process 411 to run task
[2023-04-30 09:51:52,375] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'multi_attack_dag', 'attack_CarliniL2Method', 'manual__2023-04-30T09:46:13.115621+00:00', '--job-id', '7403', '--raw', '--subdir', 'DAGS_FOLDER/attack_dag.py', '--cfg-path', '/tmp/tmpbdsyegyx', '--error-file', '/tmp/tmpz5cjj8mf']
[2023-04-30 09:51:52,385] {standard_task_runner.py:80} INFO - Job 7403: Subtask attack_CarliniL2Method
[2023-04-30 09:51:52,655] {task_command.py:369} INFO - Running <TaskInstance: multi_attack_dag.attack_CarliniL2Method manual__2023-04-30T09:46:13.115621+00:00 [running]> on host 873e5d3a4399
[2023-04-30 09:51:52,936] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=multi_attack_dag
AIRFLOW_CTX_TASK_ID=attack_CarliniL2Method
AIRFLOW_CTX_EXECUTION_DATE=2023-04-30T09:46:13.115621+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-30T09:46:13.115621+00:00
[2023-04-30 09:51:52,945] {transport.py:157} INFO - Attempting refresh to obtain initial access_token
[2023-04-30 09:51:52,967] {client.py:777} INFO - Refreshing access_token
[2023-04-30 09:51:54,790] {estimator_helpers.py:53} INFO - Getting estimator...
[2023-04-30 09:51:54,793] {transport.py:157} INFO - Attempting refresh to obtain initial access_token
[2023-04-30 09:51:54,797] {client.py:777} INFO - Refreshing access_token
[2023-04-30 09:51:55,615] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/attack.py", line 98, in attack_CarliniL2Method
    model_acc, adversarial_examples  = attack(CarliniL2Method)
  File "/opt/airflow/dags/attack.py", line 33, in attack
    estimator = get_estimator()
  File "/opt/airflow/dags/estimator_helpers.py", line 56, in get_estimator
    model = load_from_bucket("ML_model.pickle")
  File "/opt/airflow/dags/helpers.py", line 123, in load_from_bucket
    raise err
  File "/opt/airflow/dags/helpers.py", line 120, in load_from_bucket
    loaded_obj = cloudpickle.load(f)
TypeError: code() takes at most 15 arguments (16 given)
[2023-04-30 09:51:55,638] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=multi_attack_dag, task_id=attack_CarliniL2Method, execution_date=20230430T094613, start_date=20230430T095152, end_date=20230430T095155
[2023-04-30 09:51:55,661] {standard_task_runner.py:97} ERROR - Failed to execute job 7403 for task attack_CarliniL2Method (code() takes at most 15 arguments (16 given); 411)
[2023-04-30 09:51:55,707] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-04-30 09:51:55,785] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
