[2023-04-27 10:32:22,629] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: multi_attack_dag.attack_AdversarialPatch manual__2023-04-27T10:30:40.186391+00:00 [queued]>
[2023-04-27 10:32:22,800] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: multi_attack_dag.attack_AdversarialPatch manual__2023-04-27T10:30:40.186391+00:00 [queued]>
[2023-04-27 10:32:22,809] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-04-27 10:32:22,819] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-04-27 10:32:22,819] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-04-27 10:32:22,995] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): attack_AdversarialPatch> on 2023-04-27 10:30:40.186391+00:00
[2023-04-27 10:32:23,124] {standard_task_runner.py:52} INFO - Started process 5407 to run task
[2023-04-27 10:32:23,137] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'multi_attack_dag', 'attack_AdversarialPatch', 'manual__2023-04-27T10:30:40.186391+00:00', '--job-id', '6620', '--raw', '--subdir', 'DAGS_FOLDER/attack_dag.py', '--cfg-path', '/tmp/tmpy2r4jqst', '--error-file', '/tmp/tmpg1xhg1rl']
[2023-04-27 10:32:23,199] {standard_task_runner.py:80} INFO - Job 6620: Subtask attack_AdversarialPatch
[2023-04-27 10:32:23,691] {task_command.py:369} INFO - Running <TaskInstance: multi_attack_dag.attack_AdversarialPatch manual__2023-04-27T10:30:40.186391+00:00 [running]> on host e7e31d5a6603
[2023-04-27 10:32:24,295] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=multi_attack_dag
AIRFLOW_CTX_TASK_ID=attack_AdversarialPatch
AIRFLOW_CTX_EXECUTION_DATE=2023-04-27T10:30:40.186391+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-27T10:30:40.186391+00:00
[2023-04-27 10:32:24,304] {transport.py:157} INFO - Attempting refresh to obtain initial access_token
[2023-04-27 10:32:24,357] {client.py:777} INFO - Refreshing access_token
[2023-04-27 10:32:25,221] {transport.py:157} INFO - Attempting refresh to obtain initial access_token
[2023-04-27 10:32:25,228] {client.py:777} INFO - Refreshing access_token
[2023-04-27 10:32:57,819] {pytorch.py:1198} INFO - Inferred 5 hidden layers on PyTorch classifier.
[2023-04-27 10:38:19,862] {attack_dag.py:643} INFO - Optimizing...
[2023-04-27 10:38:19,877] {logging_mixin.py:115} INFO - I am right here on <class 'art.attacks.evasion.adversarial_patch.adversarial_patch.AdversarialPatch'>
[2023-04-27 10:38:19,939] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/attack_dag.py", line 525, in attack_AdversarialPatch
    model_acc, adversarial_examples  = attack(AdversarialPatch)
  File "/opt/airflow/dags/attack_dag.py", line 644, in attack
    try:
  File "/opt/airflow/dags/attack_dag.py", line 617, in optimize_evasion_attack
    search_space = [v for k, v in attack_parameter_range[attack.__name__].items()]
KeyError: 'AdversarialPatch'
[2023-04-27 10:38:20,411] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=multi_attack_dag, task_id=attack_AdversarialPatch, execution_date=20230427T103040, start_date=20230427T103222, end_date=20230427T103820
[2023-04-27 10:38:20,972] {standard_task_runner.py:97} ERROR - Failed to execute job 6620 for task attack_AdversarialPatch ('AdversarialPatch'; 5407)
[2023-04-27 10:38:21,063] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-04-27 10:38:21,720] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
