[2023-04-30 09:08:00,833] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: multi_attack_dag.attack_FastGradientMethod manual__2023-04-30T09:07:35.568192+00:00 [queued]>
[2023-04-30 09:08:00,894] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: multi_attack_dag.attack_FastGradientMethod manual__2023-04-30T09:07:35.568192+00:00 [queued]>
[2023-04-30 09:08:00,897] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-04-30 09:08:00,903] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-04-30 09:08:00,903] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-04-30 09:08:00,958] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): attack_FastGradientMethod> on 2023-04-30 09:07:35.568192+00:00
[2023-04-30 09:08:00,975] {standard_task_runner.py:52} INFO - Started process 259 to run task
[2023-04-30 09:08:00,994] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'multi_attack_dag', 'attack_FastGradientMethod', 'manual__2023-04-30T09:07:35.568192+00:00', '--job-id', '7243', '--raw', '--subdir', 'DAGS_FOLDER/attack_dag.py', '--cfg-path', '/tmp/tmp6415snhs', '--error-file', '/tmp/tmpwybiwv0p']
[2023-04-30 09:08:00,997] {standard_task_runner.py:80} INFO - Job 7243: Subtask attack_FastGradientMethod
[2023-04-30 09:08:01,163] {task_command.py:369} INFO - Running <TaskInstance: multi_attack_dag.attack_FastGradientMethod manual__2023-04-30T09:07:35.568192+00:00 [running]> on host e7e31d5a6603
[2023-04-30 09:08:01,339] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=multi_attack_dag
AIRFLOW_CTX_TASK_ID=attack_FastGradientMethod
AIRFLOW_CTX_EXECUTION_DATE=2023-04-30T09:07:35.568192+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-30T09:07:35.568192+00:00
[2023-04-30 09:08:01,381] {transport.py:157} INFO - Attempting refresh to obtain initial access_token
[2023-04-30 09:08:01,390] {client.py:777} INFO - Refreshing access_token
[2023-04-30 09:08:03,033] {transport.py:157} INFO - Attempting refresh to obtain initial access_token
[2023-04-30 09:08:03,035] {client.py:777} INFO - Refreshing access_token
[2023-04-30 09:08:04,735] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/attack.py", line 210, in attack_FastGradientMethod
    model_acc, adversarial_examples = attack(FastGradientMethod)
  File "/opt/airflow/dags/attack.py", line 33, in attack
    estimator = get_estimator()
  File "/opt/airflow/dags/estimator_helpers.py", line 53, in get_estimator
    model = load_from_bucket("ML_model.pickle")
  File "/opt/airflow/dags/helpers.py", line 123, in load_from_bucket
    raise err
  File "/opt/airflow/dags/helpers.py", line 120, in load_from_bucket
    loaded_obj = cloudpickle.load(f)
TypeError: code() takes at most 15 arguments (16 given)
[2023-04-30 09:08:04,748] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=multi_attack_dag, task_id=attack_FastGradientMethod, execution_date=20230430T090735, start_date=20230430T090800, end_date=20230430T090804
[2023-04-30 09:08:04,759] {standard_task_runner.py:97} ERROR - Failed to execute job 7243 for task attack_FastGradientMethod (code() takes at most 15 arguments (16 given); 259)
[2023-04-30 09:08:04,791] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-04-30 09:08:04,905] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
