[2023-04-09 06:58:00,611] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: multi_attack_dag.attack_BasicIterativeMethod manual__2023-04-09T06:57:35.423989+00:00 [queued]>
[2023-04-09 06:58:00,627] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: multi_attack_dag.attack_BasicIterativeMethod manual__2023-04-09T06:57:35.423989+00:00 [queued]>
[2023-04-09 06:58:00,627] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-04-09 06:58:00,628] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-04-09 06:58:00,628] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-04-09 06:58:00,643] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): attack_BasicIterativeMethod> on 2023-04-09 06:57:35.423989+00:00
[2023-04-09 06:58:00,656] {standard_task_runner.py:52} INFO - Started process 203 to run task
[2023-04-09 06:58:00,660] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'multi_attack_dag', 'attack_BasicIterativeMethod', 'manual__2023-04-09T06:57:35.423989+00:00', '--job-id', '4729', '--raw', '--subdir', 'DAGS_FOLDER/attack_dag.py', '--cfg-path', '/tmp/tmpg6fy095d', '--error-file', '/tmp/tmpfl7388h6']
[2023-04-09 06:58:00,661] {standard_task_runner.py:80} INFO - Job 4729: Subtask attack_BasicIterativeMethod
[2023-04-09 06:58:00,773] {task_command.py:369} INFO - Running <TaskInstance: multi_attack_dag.attack_BasicIterativeMethod manual__2023-04-09T06:57:35.423989+00:00 [running]> on host ff3d40af78f9
[2023-04-09 06:58:00,954] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=multi_attack_dag
AIRFLOW_CTX_TASK_ID=attack_BasicIterativeMethod
AIRFLOW_CTX_EXECUTION_DATE=2023-04-09T06:57:35.423989+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-09T06:57:35.423989+00:00
[2023-04-09 06:58:00,960] {transport.py:157} INFO - Attempting refresh to obtain initial access_token
[2023-04-09 06:58:00,965] {client.py:777} INFO - Refreshing access_token
[2023-04-09 06:58:02,069] {transport.py:157} INFO - Attempting refresh to obtain initial access_token
[2023-04-09 06:58:02,071] {client.py:777} INFO - Refreshing access_token
[2023-04-09 06:58:03,259] {transport.py:157} INFO - Attempting refresh to obtain initial access_token
[2023-04-09 06:58:03,261] {client.py:777} INFO - Refreshing access_token
[2023-04-09 06:58:03,998] {pytorch.py:1198} INFO - Inferred 5 hidden layers on PyTorch classifier.
[2023-04-09 06:58:04,001] {transport.py:157} INFO - Attempting refresh to obtain initial access_token
[2023-04-09 06:58:04,005] {client.py:777} INFO - Refreshing access_token
[2023-04-09 06:59:01,557] {projected_gradient_descent.py:199} INFO - Creating adversarial samples.
[2023-04-09 06:59:01,601] {logging_mixin.py:115} WARNING - PGD - Batches:   0%|          | 0/32 [00:00<?, ?it/s]
[2023-04-09 06:59:01,635] {logging_mixin.py:115} WARNING -                                                      
[2023-04-09 06:59:01,645] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/attack_dag.py", line 119, in attack_BasicIterativeMethod
    model_acc = attack(BasicIterativeMethod)
  File "/opt/airflow/dags/attack_dag.py", line 135, in attack
    adversarial_examples = wrap_attack.generate(np.asarray(x_train))
  File "/home/airflow/.local/lib/python3.7/site-packages/art/attacks/evasion/projected_gradient_descent/projected_gradient_descent.py", line 200, in generate
    return self._attack.generate(x=x, y=y, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_pytorch.py", line 219, in generate
    x=batch, targets=batch_labels, mask=mask_batch, eps=batch_eps, eps_step=batch_eps_step
  File "/home/airflow/.local/lib/python3.7/site-packages/art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_pytorch.py", line 280, in _generate_batch
    adv_x, inputs, targets, mask, eps, eps_step, self.num_random_init > 0 and i_max_iter == 0, momentum
  File "/home/airflow/.local/lib/python3.7/site-packages/art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_pytorch.py", line 435, in _compute_pytorch
    perturbation = self._compute_perturbation_pytorch(x_adv, y, mask, momentum)
  File "/home/airflow/.local/lib/python3.7/site-packages/art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_pytorch.py", line 307, in _compute_perturbation_pytorch
    grad = self.estimator.loss_gradient(x=x, y=y) * (1 - 2 * int(self.targeted))
  File "/home/airflow/.local/lib/python3.7/site-packages/art/estimators/classification/pytorch.py", line 843, in loss_gradient
    loss = self._loss(model_outputs[-1], labels_t)
  File "/home/airflow/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 246, in _forward_unimplemented
    raise NotImplementedError(f"Module [{type(self).__name__}] is missing the required \"forward\" function")
NotImplementedError: Module [_Loss] is missing the required "forward" function
[2023-04-09 06:59:01,665] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=multi_attack_dag, task_id=attack_BasicIterativeMethod, execution_date=20230409T065735, start_date=20230409T065800, end_date=20230409T065901
[2023-04-09 06:59:01,693] {standard_task_runner.py:97} ERROR - Failed to execute job 4729 for task attack_BasicIterativeMethod (Module [_Loss] is missing the required "forward" function; 203)
[2023-04-09 06:59:01,807] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-04-09 06:59:01,852] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
